package scene {
	import core.*;
	import gameobj.BasicStain;
	import misc.FlxGroupSprite;
	import mx.core.FlexSprite;
	import org.flixel.*;
	import particle.*;
	public class TestScene extends Scene {
		
		private static var SCRIPT:Array = [
			{PERCENT:0, CHARACTER:CHARACTER_THUG, POSITION:[340, 317], ID:1 },
			{PERCENT:0, CHARACTER:CHARACTER_THUG, POSITION:[400, 317], ID:2  },
			{PERCENT:0, CHARACTER:CHARACTER_THUG, POSITION:[450, 317], ID:3  },
			{PERCENT:0, CHARACTER:CHARACTER_THUG, POSITION:[510, 317], ID:4  },
			{PERCENT:0, CHARACTER:CHARACTER_THUG, POSITION:[590, 317], ID:5  },
			{PERCENT:0, CHARACTER:CHARACTER_THUG, POSITION:[670, 317], ID:6  },
			{PERCENT:0, CHARACTER:CHARACTER_THUG, POSITION:[720, 317], ID:7  },
			{PERCENT:0, CHARACTER:CHARACTER_THUG, POSITION:[780, 317], ID:8  },
			
			{PERCENT:0,CHARACTER:CHARACTER_ROMEO,POSITION:[267, 317]},
			{PERCENT:0, CHARACTER:CHARACTER_JULIET, POSITION:[350, 317] },
			
			{PERCENT:0.02,CHARACTER:CHARACTER_ROMEO,POSITION:[335, 317]},
			{PERCENT:0.02, CHARACTER:CHARACTER_JULIET, POSITION:[450, 317] },
			
			{PERCENT:0.06,CHARACTER:CHARACTER_ROMEO,POSITION:[460, 317]},
			{PERCENT:0.06, CHARACTER:CHARACTER_JULIET, POSITION:[600, 317], SPEED: 2 },
			
			{PERCENT:0.15,CHARACTER:CHARACTER_ROMEO,POSITION:[200, 317]},
			{PERCENT:0.15, CHARACTER:CHARACTER_JULIET, POSITION:[300, 317], SPEED: 2 },
			
			{PERCENT:0.25,CHARACTER:CHARACTER_ROMEO,POSITION:[600, 317]},
			{PERCENT:0.25,CHARACTER:CHARACTER_JULIET,POSITION:[620, 317],SPEED: 2}
		];
		
		public function TestScene(g:GameEngine) {
			super(g);
		}
		
		public override function init():Scene {
			super.init();
			load_script(SCRIPT);
			
			_bg_group.add(new BGObj(Resource.IMPORT_FLOOR1_MAINBLDG_BACK));
			_internals_group.add(new BGObj(Resource.IMPORT_FLOOR1_MAINBLDG_INTERNAL));
			_window_group.add(new BGObj(Resource.IMPORT_FLOOR1_MAINBLDG_WINDOW));
			
			return this;
		}
		
	}

}